package com.sai.app;

import com.sai.strawberry.api.CustomProcessorHook;
import com.sai.strawberry.api.EventStreamConfig;
import org.springframework.data.mongodb.core.MongoTemplate;

import java.util.HashMap;
import java.util.Map;

/**
 * Autogenerated file.
 * TODO Modify this.
 */
public class EventReceiver implements CustomProcessorHook {

    @Override
    public Map process(final EventStreamConfig eventStreamConfig, final Map eventPayload, final MongoTemplate mongoTemplate, final MongoTemplate mongoTemplateBatch) {
        // TODO implement your code.
        return new HashMap();
    }
}
