package __gid;


import com.sai.strawberry.api.EventConfig;
import com.sai.strawberry.api.MongoBackedDataTransformer;
import org.springframework.data.mongodb.core.MongoTemplate;

import java.util.HashMap;
import java.util.Map;

/**
 * Autogenerated file.
 * TODO Modify this.
 */
public class EventTransformer extends MongoBackedDataTransformer {

    @Override
    public Map process(final EventConfig eventStreamConfig, final Map map, final MongoTemplate mongoTemplate, final MongoTemplate mongoTemplateBatch) {
        // TODO implement your code.
        return new HashMap();
    }
}

